name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Primer Tests
      id: primer-tests
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Primer Tests
        setup-command: npm install
        command: npm test
        timeout: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PRIMER-TESTS_RESULTS: "${{steps.primer-tests.outputs.result}}"
      with:
        runners: primer-tests
